### ISSUE TITLE
9축 센서 동작 실현

### ISSUE THREAD

**Issue by DolySager** [DolySager/SoC_Drone#5]
MPU-9250 9축 센서 동작 방법 조사

**Comment by DolySager** [comment]
가속도축 (Accelerometer) 3축만 사용하는 방향으로 결정. 추후 비행에 문제가 될 시에 자이로 및/또는 자기계 사용 예정.

**Comment by DolySager** [comment]
- 6축만 사용하는 쪽으로 결정
- 기본 기능은 완성했으나 드리프트 현상 아직 존재

**Comment by ljh4876** [comment]
[I2C_2.zip](https://github.com/user-attachments/files/17161608/I2C_2.zip)

**Comment by DolySager** [comment]
공중 호버링 실현 목표에서 지상 밸런스 실현으로 목표 수정.
따라서 가속도 3축만 써서 Roll 과 Pitch만 감지하도록 변경.

드론은 공중 비행 특성상 지면보다는 중력에 직접적으로 영향을 받기 때문에 초기에 수행하던 지면 보정 코드를 제외함.
